apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: my-automation
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@santhoshpalani20000
        name: flux
      messageTemplate: '{{range .Updated.Images}}{{.}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  update:
    path: ./clusters/my-cluster
